### ISSUE TITLE
Issue with the New Relic Alerting for 2.2.0

### ISSUE THREAD

**Issue by skirven4** [tmartin14/splunk-newrelic#1]
Hi
   I'm trying to troubleshoot the 2.2.0 version of the app using Splunk 8.1.4 and 8.1.7.2 with respect to New Relic Alerts from Searches  We have not forced Python3 on our installation. What seems odd is that this file doesn't exist on a fresh 2.2.0 installation. It exists in 2.1.5.

`03-10-2022 09:26:00.898 -0500 INFO  sendmodalert - Invoking modular alert action=alerts_to_newrelic for search="new relic test" sid="scheduler__admin__search__RMD555c1fd397f531186_at_1646922360_55" in app="search" owner="admin" type="saved"
03-10-2022 09:26:00.935 -0500 ERROR sendmodalert - action=alerts_to_newrelic STDERR -  Traceback (most recent call last):
03-10-2022 09:26:00.935 -0500 ERROR sendmodalert - action=alerts_to_newrelic STDERR -    File "/opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/alerts_to_newrelic.py", line 9, in <module>
03-10-2022 09:26:00.935 -0500 ERROR sendmodalert - action=alerts_to_newrelic STDERR -      from alert_actions_base import ModularAlertBase
03-10-2022 09:26:00.935 -0500 ERROR sendmodalert - action=alerts_to_newrelic STDERR -  ModuleNotFoundError: No module named 'alert_actions_base'
03-10-2022 09:26:00.941 -0500 INFO  sendmodalert - action=alerts_to_newrelic - Alert action script completed in duration=39 ms with exit code=1
03-10-2022 09:26:00.941 -0500 WARN  sendmodalert - action=alerts_to_newrelic - Alert action script returned error code=1
03-10-2022 09:26:00.941 -0500 ERROR sendmodalert - Error in 'sendalert' command: Alert script returned error code 1.
03-10-2022 09:26:00.941 -0500 ERROR SearchScheduler - Error in 'sendalert' command: Alert script returned error code 1., search='sendalert alerts_to_newrelic results_file="/opt/splunk/var/run/splunk/dispatch/scheduler__admin__search__RMD555c1fd397f531186_at_1646922360_55/results.csv.gz" results_link="https://server:8443/app/search/@go?sid=scheduler__admin__search__RMD555c1fd397f531186_at_1646922360_55"'
`

Any assistance would be appreciated!

**Comment by tmartin14** [comment]
This is a known bug and will be addressed in a future release.   Apologies for the inconvenience but a couple of files were inadvertently removed in a prior build and will need to be recreated.

**Comment by skirven4** [comment]
OK Thanks! Might I ask when you think it might be rebuilt, so I can tell my users?

**Comment by tmartin14** [comment]
Hopefully in the next several weeks

**Comment by skirven4** [comment]
Please do reach out if you would like my help to test!

**Comment by tmartin14** [comment]
Thanks, will do

**Comment by tmartin14** [comment]
can you please test [this new build](https://github.com/tmartin14/splunk-newrelic/blob/master/distributions/Splunk_TA_New_Relic-2.2.1.tgz) out and let me know?

**Comment by skirven4** [comment]
Thanks! This is interesting. I see this in the logs, BUT, the event was posted to New Relic. Thanks!

`03-11-2022 16:26:01.154 -0500 INFO  sendmodalert - Invoking modular alert action=alerts_to_newrelic for search="new relic test" sid="scheduler__admin__search__RMD555c1fd397f531186_at_1647033960_41" in app="search" owner="admin" type="saved"
03-11-2022 16:26:01.156 -0500 ERROR sendmodalert - Error in 'sendalert' command: Alert action "alerts_to_newrelic" not found.
03-11-2022 16:26:01.156 -0500 ERROR SearchScheduler - Error in 'sendalert' command: Alert action "alerts_to_newrelic" not found., search='sendalert alerts_to_newrelic results_file="/opt/splunk/var/run/splunk/dispatch/scheduler__admin__search__RMD555c1fd397f531186_at_1647033960_41/results.csv.gz" results_link="https://server:8443/app/search/@go?sid=scheduler__admin__search__RMD555c1fd397f531186_at_1647033960_41"'
03-11-2022 16:26:01.794 -0500 INFO  sendmodalert - Invoking modular alert action=send_to_new_relic_insights for search="new relic test" sid="scheduler__admin__search__RMD555c1fd397f531186_at_1647033960_41" in app="search" owner="admin" type="saved"
03-11-2022 16:26:02.929 -0500 ERROR PersistentScript - From {/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/Splunk_TA_New_Relic_rh_settings.py persistent}: WARNING:root:Run function: get_password failed: Traceback (most recent call last):
03-11-2022 16:26:02.929 -0500 ERROR PersistentScript - From {/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/Splunk_TA_New_Relic_rh_settings.py persistent}:   File "/opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/splunk_ta_new_relic/aob_py3/solnlib/utils.py", line 128, in wrapper
03-11-2022 16:26:02.929 -0500 ERROR PersistentScript - From {/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/Splunk_TA_New_Relic_rh_settings.py persistent}:     return func(*args, **kwargs)
03-11-2022 16:26:02.929 -0500 ERROR PersistentScript - From {/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/Splunk_TA_New_Relic_rh_settings.py persistent}:   File "/opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/splunk_ta_new_relic/aob_py3/solnlib/credentials.py", line 133, in get_password
03-11-2022 16:26:02.929 -0500 ERROR PersistentScript - From {/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/Splunk_TA_New_Relic_rh_settings.py persistent}:     f"Failed to get password of realm={self._realm}, user={user}."
03-11-2022 16:26:02.929 -0500 ERROR PersistentScript - From {/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/Splunk_TA_New_Relic_rh_settings.py persistent}: solnlib.credentials.CredentialNotExistException: Failed to get password of realm=__REST_CREDENTIAL__#Splunk_TA_New_Relic#configs/conf-splunk_ta_new_relic_settings, user=proxy.
03-11-2022 16:26:02.929 -0500 ERROR PersistentScript - From {/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/Splunk_TA_New_Relic/bin/Splunk_TA_New_Relic_rh_settings.py persistent}: .
03-11-2022 16:26:03.213 -0500 INFO  sendmodalert - action=send_to_new_relic_insights - Alert action script completed in duration=1416 ms with exit code=200
03-11-2022 16:26:03.213 -0500 WARN  sendmodalert - action=send_to_new_relic_insights - Alert action script returned error code=200
03-11-2022 16:26:03.213 -0500 ERROR sendmodalert - Error in 'sendalert' command: Alert script returned error code 200.
03-11-2022 16:26:03.214 -0500 ERROR SearchScheduler - Error in 'sendalert' command: Alert script returned error code 200., search='sendalert send_to_new_relic_insights results_file="/opt/splunk/var/run/splunk/dispatch/scheduler__admin__search__RMD555c1fd397f531186_at_1647033960_41/results.csv.gz" results_link="https://server:8443/app/search/@go?sid=scheduler__admin__search__RMD555c1fd397f531186_at_1647033960_41"'

`

ETA: I need to check my passwords.conf. I don't think in have a config set to actually GET data. I'm only pushing to Insights from Splunk Alerts, so this error might be expected.

**Comment by tmartin14** [comment]
Did you have an older alert already configured on this Splunk instance?   I removed the 'alerts_to_newrelic' alert action and just built a new one, 'send_to_new_relic_insights'.

**Comment by skirven4** [comment]
I did have to to recreate the alert. That being said, for teams that have a lot of alerts like this, that could be a lot of work. Can we not reuse the same name?


Sent from Yahoo Mail for iPhone


On Friday, March 11, 2022, 5:07 PM, Tom Martin ***@***.***> wrote:




Did you have an older alert already configured on this Splunk instance? I removed the 'alerts_to_newrelic' alert action and just built a new one, 'send_to_new_relic_insights'.

**Comment by tmartin14** [comment]
Sure.   I’ll rename it and rebuild.  Just wanted to make sure it was working for you and me both.

**Comment by tmartin14** [comment]
Let's try this again 😉.    [This version](https://github.com/tmartin14/splunk-newrelic/blob/master/distributions/Splunk_TA_New_Relic-2.2.5.tgz) has the old name for the alert action.

**Comment by skirven4** [comment]
Thank you! This one worked in my testing with no issues. I may look more at this Monday morning, but I think we're fixed!

**Comment by tmartin14** [comment]
Thanks I’ll submit this version for cloud vetting and Splunkbase on Monday.
